apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongo # has to match .spec.template.metadata.labels
  serviceName: "mongo"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mongo # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: mongo
          image: mongo
          envFrom:
            - configMapRef:
                name: mongo-config 
          ports:
          - containerPort: 27017
            name: mongo 
          volumeMounts:
          - name: mongo
            mountPath: /data/db
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - name: mongo-service
    protocol: TCP
    port: 27017
    targetPort: 27017 