apiVersion: v1
kind: Secret
metadata:
  name: front-back-secret
  namespace: default
type: Opaque
data:
  MONGO_URL: bW9uZ29kYjovL3ZsaXN0OnZsaXN0cGFzc0Btb25nby0wLm1vbmdvLXNlcnZpY2U6MjcwMTcsbW9uZ28tMS5tb25nby1zZXJ2aWNlOjI3MDE3LG1vbmdvLTIubW9uZ28tc2VydmljZToyNzAxNy9WbGlzdERCP3JlcGxpY2FTZXQ9cnMwJmF1dGhTb3VyY2U9YWRtaW4=

  # mongodb://vlist:vlistpass@mongo-0.mongo-service:27017,mongo-1.mongo-service:27017,mongo-2.mongo-service:27017/VlistDB?replicaSet=rs0&authSource=admin
