name: deploy

on:
  workflow_run:
    workflows: [build]
    types:
      - completed
jobs:
  deploy:
   if: ${{ github.event.workflow_run.conclusion == 'success' }}

   name: Create k8s deployment
   runs-on: ubuntu-latest
   steps:
      - name: Download kubectl binaries
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
     
      - name: Install Kubectl
        run: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Authenticate with Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
      
      - name: Deploy the application
        run: |
            kubectl rollout restart deployment front-back --insecure-skip-tls-verify